global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ["IP:9100", "IP:9100", "IP:9100"]

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets: ["IP:9101", "IP:9101"]

rule_files:
  - prometheus_alerts.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - IP:9093