global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ["54.229.146.5:9100", "108.129.74.114:9100", "52.31.57.133:9100"]

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets: ["54.229.146.5:9101", "52.31.57.133:9101"]

rule_files:
  - prometheus_alerts.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 54.229.146.5:9093