all:
  children:
    controller:
      hosts:
        controller:
          ansible_host: 54.229.146.5
    target:
      hosts:
        controller:
          ansible_host: 54.229.146.5
        target-1:
          ansible_host: 108.129.74.114
        target-2:
          ansible_host: 52.31.57.133