all:
  children:
    controller:
      hosts:
        controller:
          ansible_host: 54.229.146.5
          ansible_ssh_user: ubuntu 
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/ansible-key.pem
    target:
      hosts:
        controller:
          ansible_host: 54.229.146.5
          ansible_ssh_user: ubuntu 
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/ansible-key.pem
        target-1:
          ansible_host: 108.129.74.114
          ansible_ssh_user: ubuntu 
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/ansible-key.pem
        target-2:
          ansible_host: 52.31.57.133
          ansible_ssh_user: ubuntu 
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/ansible-key.pem