all:
  children:
    controller:
      hosts:
        controller:
          ansible_host: PUBLIC_IP
    target:
      hosts:
        controller:
          ansible_host: PUBLIC_IP
        target-1:
          ansible_host: PUBLIC_IP
        target-2:
          ansible_host: PUBLIC_IP